MovieShop/MovieShop.MVC/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;

namespace MovieShop.MVC.Controllers
{
    public class MoviesController : Controller
    {
        //Always hve HttpMethod Type Attribute, by default if you dont have anything its HttpGet
        private readonly IMovieService _movieService;
        public MoviesController(IMovieService service)
        {
            _movieService = service;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var movie = await _movieService.GetMovieDetailsById(id);
            return View(movie);
        }

        [HttpGet]
        public IActionResult TopRatedMovies()
        {
            return View();
        }
        public LocalRedirectResult RedirectHome()
        {
            return LocalRedirect("~/Home/Index");
        }
    }
}

MovieShop/MovieShop.MVC/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.Models.Request;
using ApplicationCore.Models.Response;
using ApplicationCore.ServiceInterfaces;
using Infrastructure.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MovieShop.MVC.Controllers
{
    public class UserController : Controller
    {
        private readonly ICurrentUserService _currentUserSerivce;
        private readonly IUserService _userService;
        private readonly IMovieService _movieService;



        public UserController(ICurrentUserService currentUserSerivce, IUserService userService, IMovieService movieService)
        {
            _currentUserSerivce = currentUserSerivce;
            _userService = userService;
            _movieService = movieService;
        }


        [Authorize]
        [HttpGet]
        public async Task<IActionResult> GetUserPurchasesMovies()
        {
            var userId = _currentUserSerivce.UserId;
            //check whether user is loged in and 
            //if the user is not loged in redirect to login page
            //make a request to the database and get info from Purchase Table
            //select * from purchase where userid = @getfromcookie
            var purchaseMovies = await _userService.GetPurchasedMovies(userId);
            return View(purchaseMovies);
        }


        [HttpGet]
        public async Task<IActionResult> PurchaseMovie(int id)
        {
            ViewBag.movie  = await _movieService.GetMovieDetailsById(id);
            
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> PurchasesMovieAction(PurchaseMovieRequestModel purchase)
        {
            //get userId from CurrentUser and create a row in Purchase table
            await _userService.PurchaseMovie(purchase);
            return LocalRedirect("~/");
        }
        [HttpGet]
        public async Task<ActionResult> ViewProfile(int id)
        {
            ViewBag.user = await _userService.GetUserDetails(id);
            return View();
        }

        public IActionResult EditProfile()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> EditProfile(UserProfileRequestModel model)
        {
            if (ModelState.IsValid)
            {
                await _userService.EditUser(model);
            }
            return LocalRedirect("~/Account/Login");
        }

        public LocalRedirectResult RedirectHome()
        {
            return LocalRedirect("~/Home/Index");
        }

        public LocalRedirectResult RedirectEdit()
        {
            return LocalRedirect("~/User/EditProfile");
        }


    }

}

MovieShop/MovieShop.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShop.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Movie Shop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_LoginInfoPartial" />        
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MovieShop.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShop/MovieShop.MVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.Response.MovieCardResponseModel

<div class="card mb-4 shadow bg-light">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" class="img-fluid " alt="@Model.Title"/>
    </a>
</div>

MovieShop/MovieShop.MVC/Views/Shared/_loginInfoPartial.cshtml
@using ApplicationCore.ServiceInterfaces;
@inject ICurrentUserService _CurrentUserService;



@if (_CurrentUserService.IsAuthticated)
{
    // FirstName LastName and Email
    // dropdown
    // Show User Full Name along with links for logout and View and Edit Profile
    // When u click on the logout you need to call a logout method in account controller
    <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            @_CurrentUserService.FullName
        </a>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" asp-controller="User" asp-action="GetUserPurchasesMovies">Library</a>
            <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Log Out</a>
            <a class="dropdown-item" asp-controller="User" asp-route-id="@_CurrentUserService.UserId" asp-action="ViewProfile">View Profile</a>
            <a class="dropdown-item" asp-controller="User" asp-action="EditProfile">Edit Profile</a>
        </div>
    </div>

}
else
{
    <div class="navbar-collapse collapse w-100 order-3">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item pr-4">
                <a class="btn btn-outline-primary" asp-controller="Account" asp-action="Login">Login</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-outline-primary" asp-controller="Account" asp-action="Register">Register</a>
            </li>
        </ul>

    </div>
}